window:
  startup_mode: "Maximized"
  decorations: "none"
  option_as_alt: "Both"
  dynamic_padding: true

shell:
  program: /bin/zsh
  args:
    - '-l'
    - '-c'
    - 'tmux attach || tmux'

font:
  normal:
    family: JetBrainsMono Nerd Font
  size: 13

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x1f1f28'
    foreground: '0xdcd7ba'
  cursor:
   text: '0x1f1f28'
   cursor: '0xc8c093'
  vi_mode_cursor:
   text: '0x1f1f28'
   cursor: '0xc8c093'
  normal:
    black:   '0x090618'
    red:     '0xc34043'
    green:   '0x76946a'
    yellow:  '0xc0a36e'
    blue:    '0x7e9cd8'
    magenta: '0x957fb8'
    cyan:    '0x6a9589'
    white:   '0xc8c093'
  bright:
    black:   '0x727169'
    red:     '0xe82424'
    green:   '0x98bb6c'
    yellow:  '0xe6c384'
    blue:    '0x7fb4ca'
    magenta: '0x938aa9'
    cyan:    '0x7aa89f'
    white:   '0xdcd7ba'
  selection:
    background: '0x2d4f67'
    foreground: '0xc8c093'
  indexed_colors:
    - { index: 16, color: '0xffa066' }
    - { index: 17, color: '0xff5d62' }

cursor:
  style:
    shape: Block
    blinking: Always
  unfocused_hollow: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: F11, action: ToggleFullscreen }

  # # Linux
  # - { key: T,    mods: Shift|Control, command: { program: "tmux", args: ["new-window", "-c", "#{pane_current_path}"] } }
  # - { key: W,    mods: Shift|Control, command: { program: "tmux", args: ["kill-pane"] } }
  # - { key: Q,    mods: Shift|Control, command: { program: "tmux", args: ["detach-client"] } }
  # - { key: Key1, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=1"] } }
  # - { key: Key2, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=2"] } }
  # - { key: Key3, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=3"] } }
  # - { key: Key4, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=4"] } }
  # - { key: Key5, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=5"] } }
  # - { key: Key6, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=6"] } }
  # - { key: Key7, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=7"] } }
  # - { key: Key8, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=8"] } }
  # - { key: Key9, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=9"] } }
  # - { key: Key0, mods: Alt,           command: { program: "tmux", args: ["select-window", "-t", ":=10"] } }

  # - { key: N, mods: Shift|Control, command: { program: "alacritty", args: ["--command", "tmux", "new-session"] } }

  # macOS
  - { key: T,      mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["new-window", "-c", "#{pane_current_path}"] } }
  - { key: W,      mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["kill-pane"] } }
  - { key: Q,      mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["detach-client"] } }
  - { key: N,      mods: Shift|Command, command: { program: "/opt/homebrew/bin/alacritty", args: ["--command", "/opt/homebrew/bin/tmux", "new-session"] } }
  - { key: Key1,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=1"] } }
  - { key: Key2,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=2"] } }
  - { key: Key3,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=3"] } }
  - { key: Key4,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=4"] } }
  - { key: Key5,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=5"] } }
  - { key: Key6,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=6"] } }
  - { key: Key7,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=7"] } }
  - { key: Key8,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=8"] } }
  - { key: Key9,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=9"] } }
  - { key: Key0,   mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t", ":=10"] } }
  - { key: D,      mods: Command,       command: { program: "/opt/homebrew/bin/tmux", args: ["split-window", "-h"] } }
  - { key: D,      mods: Shift|Command, command: { program: "/opt/homebrew/bin/tmux", args: ["split-window"] } }
  - { key: Return, mods: Shift|Command, command: { program: "/opt/homebrew/bin/tmux", args: ["resize-pane", "-Z"] } }
