[env]
_.file = ".env"

[tools]
"npm:@playwright/cli" = "latest"
"npm:hunkdiff" = { version = "latest", trust_policy_excludes = ["@pierre/theme@2.0.0"] }
bun = "latest"
go = "latest"
node = "latest"
npm = "latest"
rust = "latest"
uv = "latest"
