[settings]
auto_update = true
auto_update_check_duration = "1d"
not_found_auto_install = true
idiomatic_version_file_enable_tools = ["node", "python"]

[dotfiles]
"~/.config/mise/config.toml" = "~/.dotfiles/mise.toml"
"~/.config/nvim" = "~/.dotfiles/nvim"

[tools]
atuin = "latest"
bat = "latest"
claude = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
hunk = "latest"
just = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
npm = "latest"
"npm:playwright" = "latest"
ripgrep = "latest"
rust = "latest"
tree-sitter = "latest"
uv = "latest"
zoxide = "latest"
