#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Google Workspace MCP (github.com/taylorwilsdon/google_workspace_mcp)
# for a single local user talking to Claude Code over streamable HTTP.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

CONFIG_DIR="$HOME/.config/workspace-mcp"
ENV_FILE="${WORKSPACE_MCP_ENV_FILE:-$CONFIG_DIR/.env}"
LAUNCHER="$CONFIG_DIR/start"
MCP_NAME="workspace-mcp"
mkdir -p "$CONFIG_DIR"

# service name → Google API id, matching the server's core/api_enablement.py
# (contacts and apps script are not in that map; ids taken from the API library).
api_for() {
  case "$1" in
    calendar) echo calendar-json.googleapis.com ;;
    drive)    echo drive.googleapis.com ;;
    gmail)    echo gmail.googleapis.com ;;
    docs)     echo docs.googleapis.com ;;
    sheets)   echo sheets.googleapis.com ;;
    slides)   echo slides.googleapis.com ;;
    forms)    echo forms.googleapis.com ;;
    tasks)    echo tasks.googleapis.com ;;
    chat)     echo chat.googleapis.com ;;
    search)   echo customsearch.googleapis.com ;;
    contacts) echo people.googleapis.com ;;
    appscript) echo script.googleapis.com ;;
    *) return 1 ;;
  esac
}

# choose_services shows a toggleable checklist of $SERVICES and sets
# WIZARD_TOOLS to the chosen ones. j/k or arrows move, space toggles, Enter
# confirms. Pre-checks whatever the env file saved on a previous run.
SERVICES=(gmail drive calendar docs sheets slides forms tasks contacts chat search appscript)
choose_services() {
  local saved cur=0 i key n=${#SERVICES[@]}
  local -a on
  saved=" $(_existing WIZARD_TOOLS || echo "gmail drive calendar docs sheets") "
  for i in "${!SERVICES[@]}"; do
    [[ "$saved" == *" ${SERVICES[$i]} "* ]] && on[i]=1 || on[i]=0
  done
  note "j/k or ↑/↓ move · space toggles · a all · n none · Enter confirms"
  printf '\033[?25l'
  while :; do
    for i in "${!SERVICES[@]}"; do
      local mark="[ ]" ptr="  "
      (( on[i] )) && mark="[${GREEN}x${RESET}]"
      (( i == cur )) && ptr="${BLUE}>${RESET} "
      printf '\033[2K  %s%s %s\n' "$ptr" "$mark" "${SERVICES[$i]}"
    done
    IFS= read -rsn1 key || key=""
    if [[ "$key" == $'\033' ]]; then
      # Integer timeout: bash 3.2 (macOS /bin/bash) rejects fractional ones.
      read -rsn2 -t 1 key || key="esc"
      case "$key" in '[A') key=k ;; '[B') key=j ;; *) key="esc" ;; esac
    fi
    case "$key" in
      j) cur=$(( (cur + 1) % n )) ;;
      k) cur=$(( (cur + n - 1) % n )) ;;
      ' ') on[cur]=$(( 1 - on[cur] )) ;;
      a) for i in "${!SERVICES[@]}"; do on[i]=1; done ;;
      n) for i in "${!SERVICES[@]}"; do on[i]=0; done ;;
      '') break ;;
    esac
    printf '\033[%dA' "$n"
  done
  printf '\033[?25h'
  WIZARD_TOOLS=""
  for i in "${!SERVICES[@]}"; do
    (( on[i] )) && WIZARD_TOOLS="${WIZARD_TOOLS:+$WIZARD_TOOLS }${SERVICES[$i]}"
  done
  if [[ -z "$WIZARD_TOOLS" ]]; then
    warn "pick at least one service"
    choose_services
  fi
}

banner "Google Workspace MCP setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites and choices"
say "The server runs with uvx and Claude Code connects to it over HTTP."
for tool in uv claude; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "✓ $tool found"
  else
    warn "$tool not found on PATH"
    SKIPPED+=("install $tool before starting the server")
  fi
done
printf '\n'
say "Pick the services to enable:"
note "Chat needs a Workspace account plus a one-time Chat app config; leave it off unless you need it."
choose_services
ask WIZARD_TOOL_TIER "Tool tier: core (lean), extended, or complete (default: core):"
[[ -z "$WIZARD_TOOL_TIER" ]] && WIZARD_TOOL_TIER=core
ask USER_GOOGLE_EMAIL "Google account email to sign in with:"
ask WORKSPACE_MCP_PORT "Local port for the server (default: 8765):"
[[ -z "$WORKSPACE_MCP_PORT" ]] && WORKSPACE_MCP_PORT=8765
[[ "$WORKSPACE_MCP_PORT" =~ ^[0-9]+$ ]] || { warn "port must be a number"; exit 1; }
MCP_URL="http://localhost:$WORKSPACE_MCP_PORT/mcp"
write_env WIZARD_TOOLS "$WIZARD_TOOLS"
write_env WIZARD_TOOL_TIER "$WIZARD_TOOL_TIER"
write_env USER_GOOGLE_EMAIL "$USER_GOOGLE_EMAIL"
write_env WORKSPACE_MCP_PORT "$WORKSPACE_MCP_PORT"
write_env WORKSPACE_MCP_HOST 127.0.0.1   # legacy HTTP mode has no MCP-level auth; never expose it

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: project"
say "Every OAuth client lives in a Cloud project. Reuse one or create a fresh one."
open_url "https://console.cloud.google.com/projectcreate"
step "Name it (e.g. 'workspace-mcp') and click Create, or close the dialog to reuse an existing project."
step "Copy the Project ID (not the name) from the project picker at the top of the console."
ask GOOGLE_CLOUD_PROJECT "Paste the project ID:"
write_env GOOGLE_CLOUD_PROJECT "$GOOGLE_CLOUD_PROJECT"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: enable APIs"
apiids=""
for svc in $WIZARD_TOOLS; do apiids="${apiids:+$apiids,}$(api_for "$svc")"; done
say "This flow enables every API your chosen services need in one go."
open_url "https://console.cloud.google.com/flows/enableapi?apiid=${apiids}&project=${GOOGLE_CLOUD_PROJECT}"
step "Confirm the project, then click Next → Enable and wait for the green ticks."
if [[ " $WIZARD_TOOLS " == *" appscript "* ]]; then
  warn "Apps Script also needs the per-user toggle: https://script.google.com/home/usersettings → Google Apps Script API → On"
fi
pause "Enabled? Press Enter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: OAuth consent screen"
say "Google shows this screen at first sign-in. External + test users keeps it out of app review."
open_url "https://console.cloud.google.com/auth/overview?project=${GOOGLE_CLOUD_PROJECT}"
step "Click Get started. App name: 'Workspace MCP'; support email: your address."
step "Audience: External. Contact email: your address. Agree and Create."
note "If the overview already shows an app, skip straight to the test users below."
pause "Consent screen created? Press Enter"
open_url "https://console.cloud.google.com/auth/audience?project=${GOOGLE_CLOUD_PROJECT}"
step "Under Test users click Add users, enter $USER_GOOGLE_EMAIL, Save."
note "In Testing status Google expires the refresh token every 7 days, so you re-sign in weekly."
note "To avoid that, publish the app: on Branding fill Homepage and Privacy policy (the upstream repo URL works for both:"
note "https://github.com/taylorwilsdon/google_workspace_mcp) and add github.com under Authorised domains, save, then Publish app on the Audience page."
note "Personal use needs no verification; you just click through an 'unverified app' warning at sign-in."
pause "Test user added? Press Enter"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: OAuth client"
say "A Desktop-app client needs no redirect URIs and covers the local HTTP server."
open_url "https://console.cloud.google.com/auth/clients/create?project=${GOOGLE_CLOUD_PROJECT}"
step "Application type: Desktop app. Name: 'workspace-mcp'. Click Create."
step "In the dialog copy the Client ID (ends in .apps.googleusercontent.com) and the Client secret."
ask GOOGLE_OAUTH_CLIENT_ID "Paste the client ID:"
ask_secret GOOGLE_OAUTH_CLIENT_SECRET "Paste the client secret:"
write_env GOOGLE_OAUTH_CLIENT_ID "$GOOGLE_OAUTH_CLIENT_ID"
write_env GOOGLE_OAUTH_CLIENT_SECRET "$GOOGLE_OAUTH_CLIENT_SECRET"
write_env OAUTHLIB_INSECURE_TRANSPORT 1   # the callback is plain http://localhost
chmod 600 "$ENV_FILE"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Launcher and Claude Code registration"
cat > "$LAUNCHER" <<LAUNCH
#!/usr/bin/env bash
# Generated by wizard/google-workspace-mcp.sh; re-run the wizard to change services.
set -euo pipefail
set -a; . "$ENV_FILE"; set +a
# shellcheck disable=SC2086
exec uvx workspace-mcp --transport streamable-http --tool-tier "\$WIZARD_TOOL_TIER" --tools \$WIZARD_TOOLS "\$@"
LAUNCH
chmod +x "$LAUNCHER"
printf '  %s✓ wrote%s launcher → %s\n' "$GREEN" "$RESET" "$LAUNCHER"
say "Start the server in another terminal now and keep it running:"
printf '\n      %s%s%s\n\n' "$BOLD" "$LAUNCHER" "$RESET"
note "First run downloads the package with uvx; wait for 'Uvicorn running on http://127.0.0.1:$WORKSPACE_MCP_PORT'."
pause "Server up? Press Enter"
if command -v claude >/dev/null 2>&1; then
  if confirm "Register $MCP_NAME with Claude Code (user scope) now?"; then
    claude mcp remove --scope user "$MCP_NAME" >/dev/null 2>&1 || true
    if claude mcp add --scope user --transport http "$MCP_NAME" "$MCP_URL"; then
      printf '  %s✓ registered%s %s → %s\n' "$GREEN" "$RESET" "$MCP_NAME" "$MCP_URL"
    else
      SKIPPED+=("claude mcp add --scope user --transport http $MCP_NAME $MCP_URL")
      warn "registration failed; run it by hand later"
    fi
  else
    SKIPPED+=("claude mcp add --scope user --transport http $MCP_NAME $MCP_URL")
  fi
else
  SKIPPED+=("claude mcp add --scope user --transport http $MCP_NAME $MCP_URL")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "First sign-in"
say "The first tool call opens Google's consent page; the server stores the refresh token under ~/.google_workspace_mcp/."
step "Open a new Claude Code session and ask e.g. 'list my 3 most recent unread emails'."
step "Sign in as $USER_GOOGLE_EMAIL. On 'Google hasn't verified this app' click Continue, then allow the scopes."
step "The browser shows a success page; the tool call completes in Claude."
note "If the call fails with an API-not-enabled error, the message links the exact enable page."
pause "Signed in? Press Enter"

finish
note "Later: start the server with $LAUNCHER, re-run this wizard to change services or rotate the secret."
