return {
  {
    "rebelot/kanagawa.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      local c = require("kanagawa.color")
      local colors = require("kanagawa.colors").setup()
      require("kanagawa").setup({
        globalStatus = true,
        overrides = {
          CursorLine = { bg = colors.bg_light0 },
          Search = { fg = "NONE", bg = colors.bg_search },

          TelescopeNormal = { bg = colors.bg_dim },
          TelescopeBorder = { fg = colors.bg_dim, bg = colors.bg_dim },
          TelescopeTitle = { fg = colors.bg_light3, bold = true },
          TelescopePromptNormal = { bg = colors.bg_light0 },
          TelescopePromptBorder = { fg = colors.bg_light0, bg = colors.bg_light0 },
          TelescopeResultsNormal = { bg = "#1a1a22" },
          TelescopeResultsBorder = { fg = "#1a1a22", bg = "#1a1a22" },
          TelescopePreviewNormal = { bg = colors.bg_dim },
          TelescopePreviewBorder = { bg = colors.bg_dim, fg = colors.bg_dim },

          CmpItemKindClass = { fg = colors.surimiOrange },
          CmpItemKindConstant = { fg = colors.oniViolet },
          CmpItemKindConstructor = { fg = colors.surimiOrange },
          CmpItemKindEnum = { fg = colors.boatYellow2 },
          CmpItemKindEnumMember = { fg = colors.carpYellow },
          CmpItemKindField = { fg = colors.waveAqua1 },
          CmpItemKindFile = { fg = colors.springViolet2 },
          CmpItemKindFunction = { fg = colors.crystalBlue },
          CmpItemKindInterface = { fg = colors.carpYellow },
          CmpItemKindKeyword = { fg = colors.oniViolet },
          CmpItemKindMethod = { fg = colors.crystalBlue },
          CmpItemKindModule = { fg = colors.boatYellow2 },
          CmpItemKindOperator = { fg = colors.springViolet2 },
          CmpItemKindProperty = { fg = colors.waveAqua2 },
          CmpItemKindStruct = { fg = colors.surimiOrange },
          CmpItemKindTypeParameter = { fg = colors.springBlue },
          CmpItemKindVariable = { fg = colors.oniViolet },

          NavicIconsArray = { fg = colors.waveAqua2 },
          NavicIconsBoolean = { fg = colors.surimiOrange },
          NavicIconsClass = { fg = colors.surimiOrange },
          NavicIconsConstant = { fg = colors.oniViolet },
          NavicIconsConstructor = { fg = colors.surimiOrange },
          NavicIconsEnum = { fg = colors.boatYellow2 },
          NavicIconsEnumMember = { fg = colors.carpYellow },
          NavicIconsEvent = { fg = colors.surimiOrange },
          NavicIconsField = { fg = colors.waveAqua1 },
          NavicIconsFile = { fg = colors.springViolet2 },
          NavicIconsFunction = { fg = colors.crystalBlue },
          NavicIconsInterface = { fg = colors.carpYellow },
          NavicIconsKey = { fg = colors.oniViolet },
          NavicIconsMethod = { fg = colors.crystalBlue },
          NavicIconsModule = { fg = colors.boatYellow2 },
          NavicIconsNamespace = { fg = colors.springViolet2 },
          NavicIconsNull = { fg = colors.carpYellow },
          NavicIconsNumber = { fg = colors.sakuraPink },
          NavicIconsObject = { fg = colors.surimiOrange },
          NavicIconsOperator = { fg = colors.springViolet2 },
          NavicIconsPackage = { fg = colors.springViolet1 },
          NavicIconsProperty = { fg = colors.waveAqua2 },
          NavicIconsString = { fg = colors.springGreen },
          NavicIconsStruct = { fg = colors.surimiOrange },
          NavicIconsTypeParameter = { fg = colors.springBlue },
          NavicIconsVariable = { fg = colors.oniViolet },
          NavicSeparator = { fg = colors.bg_light2 },
          NavicText = { fg = tostring(c(colors.bg_light2):lighten(1.5)) },

          IlluminatedWordText = { bg = colors.bg_light1 },
          IlluminatedWordRead = { bg = colors.bg_light1 },
          IlluminatedWordWrite = { bg = colors.bg_light1 },

          NeoTreeDimText = { fg = colors.bg_light2 },
          NeoTreeDotfile = { fg = colors.fg_comment },
          NeoTreeDirectoryName = { fg = colors.fg },
          NeoTreeDirectoryIcon = { fg = "#c09553" },
          NeoTreeFileIcon = { fg = colors.fg },
          NeoTreeTabInactive = { fg = colors.fg_comment, bg = colors.bg },
          NeoTreeTabActive = { fg = colors.fg, bg = colors.bg_light1 },
          NeoTreeTabSeparatorInactive = { fg = colors.bg_dark, bg = colors.bg },
          NeoTreeTabSeparatorActive = { fg = colors.bg_dark, bg = colors.bg_light1 },
          NeoTreeGitUntracked = { link = "GitSignsAdd" },

          IndentBlanklineChar = { fg = colors.bg_light0 },
          IndentBlanklineSpaceChar = { fg = colors.bg_light0 },
          IndentBlanklineSpaceCharBlankline = { fg = colors.bg_light0 },
          IndentBlanklineContextChar = { fg = colors.bg_light1 },
        },
      })

      vim.cmd("colorscheme kanagawa")
    end,
  },
}
