local colors = require("kanagawa.colors").setup()
require("kanagawa").setup({
  globalStatus = true,
  overrides = {
    CursorLine = { bg = colors.bg_light0 },
    Search = { fg = "NONE", bg = colors.bg_search },

    TelescopeNormal = { bg = colors.bg_dim },
    TelescopeBorder = { fg = colors.bg_dim, bg = colors.bg_dim },
    TelescopeTitle = { fg = colors.bg_light3, bold = true },
    TelescopePromptNormal = { bg = colors.bg_light0 },
    TelescopePromptBorder = { fg = colors.bg_light0, bg = colors.bg_light0 },
    TelescopeResultsNormal = { bg = "#1a1a22" },
    TelescopeResultsBorder = { fg = "#1a1a22", bg = "#1a1a22" },
    TelescopePreviewNormal = { bg = colors.bg_dim },
    TelescopePreviewBorder = { bg = colors.bg_dim, fg = colors.bg_dim },

    NavicIconsFile = { fg = colors.springViolet2 },
    NavicIconsModule = { fg = colors.boatYellow2 },
    NavicIconsNamespace = { fg = colors.springViolet2 },
    NavicIconsPackage = { fg = colors.springViolet1 },
    NavicIconsClass = { fg = colors.surimiOrange },
    NavicIconsMethod = { fg = colors.crystalBlue },
    NavicIconsProperty = { fg = colors.waveAqua2 },
    NavicIconsField = { fg = colors.waveAqua1 },
    NavicIconsConstructor = { fg = colors.surimiOrange },
    NavicIconsEnum = { fg = colors.boatYellow2 },
    NavicIconsInterface = { fg = colors.carpYellow },
    NavicIconsFunction = { fg = colors.crystalBlue },
    NavicIconsVariable = { fg = colors.oniViolet },
    NavicIconsConstant = { fg = colors.oniViolet },
    NavicIconsString = { fg = colors.springGreen },
    NavicIconsNumber = { fg = colors.sakuraPink },
    NavicIconsBoolean = { fg = colors.surimiOrange },
    NavicIconsArray = { fg = colors.waveAqua2 },
    NavicIconsObject = { fg = colors.surimiOrange },
    NavicIconsKey = { fg = colors.oniViolet },
    NavicIconsNull = { fg = colors.carpYellow },
    NavicIconsEnumMember = { fg = colors.carpYellow },
    NavicIconsStruct = { fg = colors.surimiOrange },
    NavicIconsEvent = { fg = colors.surimiOrange },
    NavicIconsOperator = { fg = colors.springViolet2 },
    NavicIconsTypeParameter = { fg = colors.springBlue },
    NavicText = { fg = colors.fujiWhite },
    NavicSeparator = { fg = colors.fujiWhite },

    IlluminatedWordText = { bg = colors.bg_light1 },
    IlluminatedWordRead = { bg = colors.bg_light1 },
    IlluminatedWordWrite = { bg = colors.bg_light1 },

    NeoTreeDimText = { fg = colors.bg_light2 },
    NeoTreeDotfile = { fg = colors.fg_comment },
    NeoTreeDirectoryName = { fg = colors.fg },
    NeoTreeDirectoryIcon = { fg = "#c09553" },
    NeoTreeFileIcon = { fg = colors.fg },
    NeoTreeTabInactive = { fg = colors.fg_comment, bg = colors.bg },
    NeoTreeTabActive = { fg = colors.fg, bg = colors.bg_light1 },
    NeoTreeTabSeparatorInactive = { fg = colors.bg_dark, bg = colors.bg },
    NeoTreeTabSeparatorActive = { fg = colors.bg_dark, bg = colors.bg_light1 },
  },
})

vim.cmd([[colorscheme kanagawa]])
